shield/urls.py
from django.contrib import admin
from django.urls import path

import commons.views
import metahumans.views

urlpatterns = [
    path('', commons.views.homepage, name="homepage"),
    path('admin/', admin.site.urls),
    path('activos/', metahumans.views.list_all_metahumans, name='metahumans'),
    path('equipos/', metahumans.views.list_all_teams, name='teams'),
    path('equipos/<slug>/', metahumans.views.detail_team, name='team_detail'),
]

commons/models.py
from django.db import models

# Create your models here.

metahumans/models.py
from django.db import models

# Create your models here.

class Team(models.Model):

    class Meta:
        verbose_name = "Equipo"
        verbose_name_plural = "Equipos"

    name = models.CharField(max_length=220)
    description = models.TextField(max_length=4000)
    headquarter =  models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Power(models.Model):

    class Meta:
        verbose_name = "Poder"
        verbose_name_plural = "Poderes"
        ordering = ['name']

    name = models.CharField(max_length=32)
    description = models.CharField(max_length=300)
    level = models.IntegerField(default=50)

    def __str__(self):
        return self.name


COUNTRIES = [
    ('US', 'United states'),
    ('ES', 'Spain'),
    ('UK', 'United Kingdom'),
    ('PL', 'Polonia'),
    ('WK', 'Wakanda'),
    ('LV', 'Lavteria'),
    ('RU', 'Rusia'),
    ('OT', "Others"),
    ]


class MetaHuman(models.Model):

    class Meta:
        verbose_name = "Metahumano"
        verbose_name_plural = "Metahumanos"

    name = models.CharField(max_length=42)
    country = models.CharField(max_length=2, choices=COUNTRIES)
    level = models.IntegerField(default=10)
    active = models.BooleanField(default=True)
    powers = models.ManyToManyField(Power)
    last_update = models.DateTimeField(auto_now=True)
    team = models.ForeignKey(
        Team,
        on_delete=models.PROTECT,
        blank=True,
        null=True,
        default=None,
    )

    def __str__(self):
        return self.name

commons/views.py
from django.shortcuts import render

# Create your views here.

def homepage(request):
    return render(request, "homepage.html")

metahumans/views.py
from django.shortcuts import render

from .models import MetaHuman, Team

# Create your views here.

def list_all_metahumans(request):
    items = MetaHuman.objects.all()
    return render(request, "metahumans/list_metahumans.html", {
        "items": items,
    })


def list_all_teams(request):
    items = Team.objects.all()
    return render(request, "metahumans/list_teams.html", {
        "items": items,
    })


def detail_team(request, slug):
    team = Team.objects.get(slug=slug)
    return render(request, "metahumans/detail_team.html", {
        "team": team,
    })

commons/templates/base.html
{% load leaflet_tags %}
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %} SHIELD {% endblock title %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    {% block js %}{% endblock %}
    {% block css %}{% endblock %}
  </head>
  <body>
  <section class="section">
    <div class="container">
        
        {% include "navbar.html" %}

        {% block content %}
        
        {% endblock content %}

    </div>
  </section>
  </body>
</html>

commons/templates/homepage.html
{% extends "base.html" %}
{% load leaflet_tags %}
{% load static %}

{% block js %}{% leaflet_js %}{% endblock %}
{% block css %}{% leaflet_css %}{% endblock %}

{% block title %}SHIELD Homepage{% endblock title %}


{% block content %}

<div class="hero">
  <div class="hero-body>
          
    <h1 class="title">SHIELD</h1>
    <h2 class="subtitle">Strategic Homeland Intervention, Enforcement, and Logistics Division</h2>

    <p class="is-size-1 has-text-right">Welcome to our webpage!</p>

  </div>    
</div>

<div class="columns">
    <div class="column is-one-third">
        <img src="{% static 'logo.png' %}">
    </div>
    <div class="column">
        {% leaflet_map "globalmap" %}
    </div>
</div>


{% endblock content %}

commons/templates/navbar.html
{% load static %}

<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
        <img src="{% static 'logo.png' %}" width="32" height="32">
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">

    <div class="navbar-start">
        <a class="navbar-item" href="{% url 'homepage' %}">
        Inicio
        </a>

        <a class="navbar-item" href="{% url 'metahumans' %}">
        Metahumanos
      </a>

      <a class="navbar-item" href="{% url 'teams' %}">
        Equipos
      </a>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            About
          </a>
          <a class="navbar-item">
            Jobs
          </a>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a class="button is-primary">
            <strong>Sign up</strong>
          </a>
          <a class="button is-light">
            Log in
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>

metahumans/templates/metahumans/detail_team.html
{% extends 'base.html' %}
{% load shield_filters %}

{% block title %}
    {{ team.name }}
{% endblock title %}

{% block content %}

<section class="hero is-info">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
          {{ team.name }}
      </h1>
      <h2 class="subtitle">
         {{ team.description }} 
      </h2>
      <p><b>Base de operaciones</b>: {{ team.headquarter }}</p>
    </div>
  </div>
</section>

<h2 class="title">
    {{ team.metahuman_set.all.count }}
    Componentes
    </span>
</h2>

<table class="table is-fullwidth is-striped">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Nivel de amenaza</th>
            <th>Poderes</th>
        </tr>
    </thead>

    {% for mh in team.metahuman_set.all %}
    <tr>
        <td> {{ mh.name }} </td>
        <td> {{ mh.level|danger_level }} </td>
        <td> 
            {% for power in mh.powers.all %}
                {{ power }}
            {% endfor %}
        </td>
    </tr> 
    {% endfor %}
</table>


{% endblock content %}

metahumans/templates/metahumans/list_metahumans.html
{% extends "base.html" %}
{% load shield_filters %}

{% block title %} Listado de metahumanos conocidos {% endblock %}

{% block content %}

<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Nivel de amenaza</th>
            <th>Equipo</th>
            <th>Poderes</th>
        </tr>
    </thead>

    {% for mh in items %}
    <tr>
        <td> {{ mh.name }} </td>
        <td> {{ mh.level|danger_level }} </td>
        <td> 
            {% if mh.team %}
               {{ mh.team }}
            {% endif %}
        </td>
        <td> 
            {% for power in mh.powers.all %}
                {{ power }}
            {% endfor %}
        </td>
    </tr> 
    {% endfor %}
</table>

{% endblock content %}

metahumans/templates/metahumans/list_teams.html
{% extends "base.html" %}
{% load shield_filters %}

{% block title %} Listado de equipos conocidos {% endblock %}

{% block content %}

<div class="columns is-multiline is-mobile">
    
{% for team in items  %}
    <div class="column is-half">
        <h2 class="title">
            <a href="{% url 'team_detail' slug=team.slug %}">
            {{ team.name }}
            </a>
        </h2>
        <h3 class="subtitle">{{ team.description }}</h3>
    </div>
{% endfor %}

</div>

{% endblock content %}